#!/usr/bin/env bash

# Check if script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo)."
  exit
fi

# Installs, configures, and inits the server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		 try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
	    rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

echo -e "$SERVER_CONFIG" > /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
   service nginx start
else
   service nginx restart
fi

